version: '3.9'

services:
  app:
    build: .
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - ${POSTGRES_HOST}
    command: uvicorn app.main:app --host ${APP_HOST} --port ${APP_PORT}
    volumes:
      - .:/code

  postgres:
    image: postgres
    container_name: ${POSTGRES_HOST}
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  mongo:
    image: mongo:6.0.4-jammy
    container_name: ${MONGO_HOST}
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}


  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=nikon2283@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    depends_on:
      - postgres
    volumes:
      - ./pgdata:/data/db