version: '3.9'

services:
  mongo:
    image: mongo:6.0.4-jammy
    container_name: mongo-da
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ADMIN_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${ADMIN_MONGO_PASSWORD}
